### ISSUE TITLE
Allow setting of `fingerprint` for grouping exceptions

### ISSUE THREAD

**Issue by samhandev** [camdez/honeybadger#6]
I'm currently working on a project that sends exceptions with `ex-info`. This seems to group all the notifications in the same bucket.

It seems `HoneyBadger` supports an extra parameter, `fingerprint` for grouping similar exceptions:
http://docs.honeybadger.io/ruby/getting-started/customizing-error-grouping.html

Does it make sense to implement this as a part of the `metadata` in your library?

I assume this is the function that will need the changes:
https://github.com/camdez/honeybadger/blob/master/src/honeybadger/core.clj#L70

Let me know what you think and I'll do a PR with changes.

Thanks!

**Comment by samhandev** [comment]
Actually looks like adding `component` to the map seems to do the same job.

**Comment by camdez** [comment]
@samhandev This is the first time I've heard of the `fingerprint` parameter, but briefly exploring it, I'm pretty sure it has a different usage from `component`; `component` is supposed to be a broad grouping construct where you can say an issue happened in the request handler, or the a background job, or whatever makes sense for your application. `fingerprint` sounds like it is the mechanism that stacks each "occurrence" into a single "error" within the UI.

If you're still interested in working on this, let's talk a bit more about the approach: are you suggesting that the user add this information into the context on a per-error basis? Because my inclination would be to say that you'd want to globally define a function that derived the fingerprints.

I'm also curious about your motivations / use cases. I've had good success with Honeybadger even without supplying a `fingerprint`; their defaults seem sensible.

**Comment by samhandev** [comment]
Hey @camdez,

We've been using `ex-info` for our errors and it seems like`HB` is grouping all of those in the same group due to the first line of the `staketrace` being `core.clj:4617 :in clojure.core/ex-info`.

For now we've added a macro which calls `*ns*` and adds that value to `component` in the context map. This has limitations of all the `HB` in the same namespace being grouped together so I may try adding `action` to the context map to see if that changes the grouping.

**Comment by camdez** [comment]
@samhandev Gotcha. Please let me know how your experiments go! Unfortunately some of this stuff is not well documented, so prodding and exploration is an essential part of the process.

Also I should probably call out this change I made recently: https://github.com/camdez/honeybadger/commit/5d10ac29d916d4996675e1810a510dcde22a78f2.  That's in the 0.3.0 release. I suspect it could have an impact on the grouping of (many) exceptions.
